name: InfiniteHomesPLUS
version: 1.3+-preview
main: com.user404_.infinitehomes.InfiniteHomes
website: https://github.com/deutschich/InfiniteHomesPLUS/
api-version: 1.21
commands:
  sethome:
    description: Set a home with the given name.
    usage: /sethome <name>
  delhome:
    description: Delete a home with the given name.
    usage: /delhome <name>
    aliases: [deletehome]
  home:
    description: Teleport to a home with the given name.
    usage: /home <name>
    aliases: [h]
  homes:
    description: List all your homes.
    usage: /homes
    aliases: [listhomes]
  homecount:
    description: Set the global home limit (OP only).
    usage: /homecount <number>
  homecooldown:
    description: Set the global home cooldown (OP only).
    usage: /homecooldown <seconds>
  setglobalhome:
    description: Set a global home accessible to all players (OP only)
    usage: /setglobalhome <name>
    aliases: [sgh]
  globalhome:
    description: Teleport to a global home
    usage: /globalhome <name>
    aliases: [gh]
  globalhomes:
    description: List all global homes
    usage: /globalhomes
    aliases: [listglobalhomes]
  delglobalhome:
    description: Delete a global home (OP only)
    usage: /delglobalhome <name>
    aliases: [deleteglobalhome, dgh]
  setplayerhome:
    description: Set a player home accessible to all players
    usage: /setplayerhome <name>
    aliases: [sph]
  playerhome:
    description: Teleport to a player home
    usage: /playerhome <name>
    aliases: [ph]
  playerhomes:
    description: List all player homes
    usage: /playerhomes
    aliases: [phs, listplayerhomes]
  delplayerhome:
    description: Delete a player home (Team members only)
    usage: /delplayerhome <name>
    aliases: [dph, deleteplayerhome]
permissions:
  infinitehomes.playerhomes.allowed:
    description: Allows setting player homes
    default: true
  infinitehomes.playerhomes.delete:
    description: Allows deleting player homes (Team members only)
    default: op